version: '3.1' # specify docker-compose version

services:
  # Runs from the latest release
  matrix-reminder-bot:
    image: anoa/matrix-reminder-bot
    restart: always
    volumes:
      - ../data:/data
    # Used for allowing connections to homeservers hosted on the host machine
    # (while docker host mode is still broken on Linux).
    #
    # Defaults to 127.0.0.1 and is set in docker/.env
    #extra_hosts:
    #  - "localhost:${HOST_IP_ADDRESS}"

  local-checkout:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      # Build arguments may be specified here
      # args:
      #  PYTHON_VERSION: 3.12
    volumes:
      - ../data:/data

  # Starts up a postgres database
  postgres:
    image: postgres
    restart: always
    volumes:
      - ../pg_data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: v2f505f4TA5SZU1M
